image: openjdk:8-jdk

stages:
  - build
  - publish


###########################
# Build
###########################
build-jar:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew assemble
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches


###########################
# Publish
###########################
publish-jar:
  stage: publish
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - echo "${PLUGIN_TOKEN}" | tr -d '\r' > ${GRADLE_USER_HOME}/gradle.properties
  script:
    - ./gradlew build publishPlugins
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  only:
    - tags
